name: Build & SonarQube Scan for Nuxt

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20' # Prueba con 20 si puedes

      - name: Upgrade npm
        run: npm install -g npm@latest

      - name: Clean install
        run: |
          rm -rf node_modules package-lock.json
          npm install

      - name: Build (Nuxt)
        run: npm run build

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        with:
          projectBaseDir: .
          args: >
            -Dsonar.organization=my-org
            -Dsonar.projectKey=SITS-FRONT
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
